apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: 570430250751.dkr.ecr.ap-southeast-1.amazonaws.com/service-a:dev-v1.0.15
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
